Repository powsybl/powsybl.github.io, pull requests merged in 2024-02, with the labels that each got.

#307 Documentation about CGMES export parameters: model-version and business-process.
  pages/documentation/grid/formats/cim-cgmes.md
Labels: PR: ready-to-be-merged

#297 Update following changes in diagram APIs
  pages/documentation/developer/api_guide/svg-writing.md
  pages/documentation/developer/tutorials/diagram/img/nad-writing/nad300.jpg
  pages/documentation/developer/tutorials/diagram/img/nad-writing/partial_diagram_1_25.svg
  pages/documentation/developer/tutorials/diagram/img/nad-writing/partial_diagram_25.svg
  pages/documentation/developer/tutorials/diagram/img/svg-writing/example_AmsterdamSubstation.svg
  pages/documentation/developer/tutorials/diagram/img/svg-writing/example_Brussels110.svg
  pages/documentation/developer/tutorials/diagram/img/svg-writing/example_a.svg
  pages/documentation/developer/tutorials/diagram/img/svg-writing/example_c.svg
  pages/documentation/developer/tutorials/diagram/img/svg-writing/example_n.svg
  pages/documentation/developer/tutorials/diagram/nad-svg-writing.md
  pages/documentation/developer/tutorials/diagram/svg-writing.md
Labels: PR: next-release

#296 [Shortcircuit] Add documentation about new parameters
  pages/documentation/developer/api_guide/short-circuit.md
  pages/documentation/grid/formats/ucte-def.md
  pages/documentation/grid/model/extensions.md
  pages/documentation/simulation/shortcircuitanalysis/index.md
  pages/documentation/user/configuration/simulation-parameters.md
Labels: PR: next-release, PR: waiting-for-review
